### ISSUE TITLE
 Define Architecture

### ISSUE THREAD

**Issue by gdeusdara** [UnBArqDsw/2020.1_G2_TCLDL#51]
Define architecture and document it

**Comment by gdeusdara** [comment]
Meeting Wednesday 6 pm

**Comment by lorryaze** [comment]
At the meeting of 09/16/2020, we decided on the stack that will be used in the development of the site and talked about the possible architectures that we will adopt for the project, the most likely architecture so far is Domain-driven design (DDD) .

At the meeting that will take place on the 18th we will decide the architecture, review the static modeling documents and update the documentation with them.
