### ISSUE TITLE
 UML Notation - Static Diagrams

### ISSUE THREAD

**Issue by gdeusdara** [UnBArqDsw/2020.1_G2_TCLDL#52]
Everyone has to make at least 1 diagram of each type

**Comment by lorryaze** [comment]
The group was divided into 2 teams that will do the static and dynamic modeling referring to the backend, frontend and database.

The teams had the following division:

Backend and database group: 
- Mikhaelle 
- Ygor 
- Vitor

Frontend group: 
- Guilherme 
- Lorrany

**Comment by Mikhaelle** [comment]
same issue of #57. Which is to be used @gdeusdara ?
