### ISSUE TITLE
Review And Update Requirements Documents

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#63]
**_Issue_ type**

HF X - Review And Update Requirements Documents 

**Description**

Review And Update Requirements Documents(minus the prototype) with all new changes.

**Screenshots**

If you think that it would be necessary, add screenshots here to help you explain your _issue_.

**Tasks**
- [ ] Review and update charts requirements.

**Acceptance Criteria**
- [ ] criteria 1
- [ ] ...

**Comment by Mikhaelle** [comment]
Requirements that need update:

- Mind Map
- Argumentation
- Rich Picture
- Moscow
- Backlog
- Lexicons

**Comment by mansogf** [comment]
I will do: 

- Mind map;
- Moscow;
- Backlog;

**Comment by lorryaze** [comment]
I will do:

- Argumentation

**Comment by Mikhaelle** [comment]
Rick PIcture and lexicons update
